apiVersion: v2
name: project5
description: A Helm chart for Project-5 multi-cloud enterprise application
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - multi-cloud
  - enterprise
  - microservices
  - kubernetes

home: https://github.com/eugenyefimov/Project-5
sources:
  - https://github.com/eugenyefimov/Project-5

maintainers:
  - name: Yevhen Yefimov
    email: shukuga@outlook.com
    url: https://yevhen.created.app

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

annotations:
  category: Application
  licenses: MIT