# Default values for project5
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: project5
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: project5.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: project5-frontend
    tag: "latest"
  service:
    port: 80
    targetPort: 80

# Backend API configuration
backendApi:
  enabled: true
  replicaCount: 2
  image:
    repository: project5-backend-api
    tag: "latest"
  service:
    port: 8000
    targetPort: 8000

# Microservices configuration
microservices:
  userService:
    enabled: true
    replicaCount: 1
    image:
      repository: user-service
      tag: "latest"
    service:
      port: 3001
      targetPort: 3001

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: "project5"
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi

# Monitoring
monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
  jaeger:
    enabled: true